<?php
return array(
    "database"=>array(
        "host"=>"localhost",
        "username"=>"root",
        "password"=>"",
        "dbname"=>"test",
        "port"=>3308
    ),
    "smarty"=>array(
        "templateDir"=>TPL_PATH,
        "compileDir"=>COMPILE_PATH,
        "cacheDir"=>CACHE_PATH,
    ),
    "code"=>array(
        "type"=>"png",
        "width"=>160,
        "height"=>50,
        "codeLen"=>4,
        "seed"=>"abcdefhjkmnprstvwxyABCDEFGHJKMNPQRSTUVWXY345678",
        "fontSize"=>array("min"=>20,"max"=>35),
        "fontAngle"=>array("min"=>-15,"max"=>15),
        "lineNum"=>array("min"=>2,"max"=>4),
        "lineWidth"=>array("min"=>1,"max"=>3),
        "pixNum"=>array("min"=>80,"max"=>150),
        "fontFile"=>"C:/wamp64/www/study/mvc\application\static/font/verdanai.ttf",
        "ischeck"=>false
    )
);